# docker-compose.yml

version: '3'

services:
  milf-bot:
    build: .
    volumes:
    - ./src/database:/app/database
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
