# docker-compose.yml

services:
  milf-bot:
    build: .
    volumes:
    - ./database:/app/database
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
